insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into orders(order_date,status , cid,uid) values("11/11/4044","fuyyuuy",4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart(total , pid,uid) values(434,4,4);
insert into cart (total, pid, uid) values (4, 4, 55);
insert into cart (total, pid, uid) values (3, 3, 49);
insert into cart (total, pid, uid) values (, , 44);
insert into cart (total, pid, uid) values (5, 5, 7);
insert into cart (total, pid, uid) values (6, 6, 44);
insert into cart (total, pid, uid) values (7, 7, 88);
insert into cart (total, pid, uid) values (8, 8, 9);
insert into cart (total, pid, uid) values (9, 9, 4);
insert into cart (total, pid, uid) values (44, 44, 93);
insert into cart (total, pid, uid) values (44, 44, 84);
insert into cart (total, pid, uid) values (44, 44, 6);
insert into cart (total, pid, uid) values (43, 43, 86);
insert into cart (total, pid, uid) values (4, 4, 84);
insert into cart (total, pid, uid) values (45, 45, 5);
insert into cart (total, pid, uid) values (46, 46, 4);
insert into cart (total, pid, uid) values (47, 47, 57);
insert into cart (total, pid, uid) values (48, 48, 45);
insert into cart (total, pid, uid) values (49, 49, 43);
insert into cart (total, pid, uid) values (44, 44, 78);
insert into cart (total, pid, uid) values (44, 44, 34);
insert into cart (total, pid, uid) values (44, 44, 65);
insert into cart (total, pid, uid) values (43, 43, 64);
insert into cart (total, pid, uid) values (4, 4, 34);
insert into cart (total, pid, uid) values (45, 45, 4);
insert into cart (total, pid, uid) values (46, 46, 49);
insert into cart (total, pid, uid) values (47, 47, 87);
insert into cart (total, pid, uid) values (48, 48, 43);
insert into cart (total, pid, uid) values (49, 49, 54);
insert into cart (total, pid, uid) values (34, 34, 87);
insert into cart (total, pid, uid) values (34, 34, 4);
insert into cart (total, pid, uid) values (34, 34, 4);
insert into cart (total, pid, uid) values (33, 33, 85);
insert into cart (total, pid, uid) values (3, 3, 87);
insert into cart (total, pid, uid) values (35, 35, 48);
insert into cart (total, pid, uid) values (36, 36, 4);
insert into cart (total, pid, uid) values (37, 37, );
insert into cart (total, pid, uid) values (38, 38, 96);
insert into cart (total, pid, uid) values (39, 39, 44);
insert into cart (total, pid, uid) values (4, 4, 33);
insert into cart (total, pid, uid) values (4, 4, 46);
insert into cart (total, pid, uid) values (4, 4, 55);
insert into cart (total, pid, uid) values (3, 3, 76);
insert into cart (total, pid, uid) values (, , 7);
insert into cart (total, pid, uid) values (5, 5, 75);
insert into cart (total, pid, uid) values (6, 6, 99);
insert into cart (total, pid, uid) values (7, 7, 53);
insert into cart (total, pid, uid) values (8, 8, 64);
insert into cart (total, pid, uid) values (9, 9, 68);
insert into cart (total, pid, uid) values (54, 54, 74);
