insert into products (name, quantity, price, description) values ('Gerhardine', 'Scholcroft', 76, '​');
insert into products (name, quantity, price, description) values ('Sher', 'Ferrige', 96, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into products (name, quantity, price, description) values ('Lottie', 'Ollerenshaw', 41, '(｡◕ ∀ ◕｡)');
insert into products (name, quantity, price, description) values ('Hanni', 'Blatchford', 34, 'nil');
insert into products (name, quantity, price, description) values ('Winthrop', 'Yewdell', 95, '🐵 🙈 🙉 🙊');
insert into products (name, quantity, price, description) values ('Jesselyn', 'Rutigliano', 73, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into products (name, quantity, price, description) values ('Ashlin', 'Szymanowicz', 29, '😍');
insert into products (name, quantity, price, description) values ('Alessandro', 'Blenkinship', 70, '😍');
insert into products (name, quantity, price, description) values ('Genna', 'Crossland', 49, '⁰⁴⁵');
insert into products (name, quantity, price, description) values ('Ogden', 'Pollie', 58, ' test ');
insert into products (name, quantity, price, description) values ('Vikki', 'Haythorne', 65, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into products (name, quantity, price, description) values ('Kalle', 'Cardoe', 71, '() { _; } >_[$($())] { touch /tmp/blns.shellshock2.fail; }');
insert into products (name, quantity, price, description) values ('Adara', 'Braksper', 22, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into products (name, quantity, price, description) values ('Golda', 'Sive', 65, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into products (name, quantity, price, description) values ('Nickie', 'Caslane', 3, '1;DROP TABLE users');
insert into products (name, quantity, price, description) values ('Randolph', 'Goadbie', 8, 'ÅÍÎÏ˝ÓÔÒÚÆ☃');
insert into products (name, quantity, price, description) values ('Willetta', 'Dorney', 87, '-1.00');
insert into products (name, quantity, price, description) values ('Lydon', 'Cluse', 63, '｀ｨ(´∀｀∩');
insert into products (name, quantity, price, description) values ('Benedikta', 'O''Kynsillaghe', 10, '1''; DROP TABLE users--');
insert into products (name, quantity, price, description) values ('Darleen', 'Tschierse', 50, '$1.00');
insert into products (name, quantity, price, description) values ('Sibeal', 'Tebbs', 64, '1''; DROP TABLE users--');
insert into products (name, quantity, price, description) values ('Cole', 'Smurfitt', 6, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into products (name, quantity, price, description) values ('Dag', 'Ratie', 5, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into products (name, quantity, price, description) values ('Inge', 'Calkin', 82, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into products (name, quantity, price, description) values ('Wendy', 'Dowzell', 48, '-1/2');
insert into products (name, quantity, price, description) values ('Sharon', 'Pavlenkov', 55, null);
insert into products (name, quantity, price, description) values ('Bernarr', 'Turland', 76, '⁰⁴⁵');
insert into products (name, quantity, price, description) values ('Alfie', 'Rickersey', 4, 'nil');
insert into products (name, quantity, price, description) values ('Alis', 'Cranefield', 40, '<script>alert(''hi'')</script>');
insert into products (name, quantity, price, description) values ('Aloysia', 'Crickmore', 20, '-1.00');
insert into products (name, quantity, price, description) values ('Artemas', 'Kwietak', 88, '"');
insert into products (name, quantity, price, description) values ('Beatrice', 'Willicott', 100, '''''');
insert into products (name, quantity, price, description) values ('Mordecai', 'McCuis', 100, 'nil');
insert into products (name, quantity, price, description) values ('Huberto', 'Paling', 56, 'パーティーへ行かないか');
insert into products (name, quantity, price, description) values ('Madelina', 'Riste', 85, ' ');
insert into products (name, quantity, price, description) values ('Leanora', 'Manicomb', 21, '""');
insert into products (name, quantity, price, description) values ('Dino', 'Midford', 38, '0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟');
insert into products (name, quantity, price, description) values ('Nissa', 'Denham', 61, '1;DROP TABLE users');
insert into products (name, quantity, price, description) values ('Llewellyn', 'Belsham', 90, 'œ∑´®†¥¨ˆøπ“‘');
insert into products (name, quantity, price, description) values ('Yoko', 'Gennings', 69, 'test⁠test‫');
insert into products (name, quantity, price, description) values ('Vyky', 'Moorwood', 85, '␢');
insert into products (name, quantity, price, description) values ('Benedetto', 'Kmieciak', 87, '̗̺͖̹̯͓Ṯ̤͍̥͇͈h̲́e͏͓̼̗̙̼̣͔ ͇̜̱̠͓͍ͅN͕͠e̗̱z̘̝̜̺͙p̤̺̹͍̯͚e̠̻̠͜r̨̤͍̺̖͔̖̖d̠̟̭̬̝͟i̦͖̩͓͔̤a̠̗̬͉̙n͚͜ ̻̞̰͚ͅh̵͉i̳̞v̢͇ḙ͎͟-҉̭̩̼͔m̤̭̫i͕͇̝̦n̗͙ḍ̟ ̯̲͕͞ǫ̟̯̰̲͙̻̝f ̪̰̰̗̖̭̘͘c̦͍̲̞͍̩̙ḥ͚a̮͎̟̙͜ơ̩̹͎s̤.̝̝ ҉Z̡̖̜͖̰̣͉̜a͖̰͙̬͡l̲̫̳͍̩g̡̟̼̱͚̞̬ͅo̗͜.̟');
insert into products (name, quantity, price, description) values ('Marilee', 'Kas', 83, '⁰⁴⁵');
insert into products (name, quantity, price, description) values ('Venus', 'Drews', 71, 'Ṱ̺̺̕o͞ ̷i̲̬͇̪͙n̝̗͕v̟̜̘̦͟o̶̙̰̠kè͚̮̺̪̹̱̤ ̖t̝͕̳̣̻̪͞h̼͓̲̦̳̘̲e͇̣̰̦̬͎ ̢̼̻̱̘h͚͎͙̜̣̲ͅi̦̲̣̰̤v̻͍e̺̭̳̪̰-m̢iͅn̖̺̞̲̯̰d̵̼̟͙̩̼̘̳ ̞̥̱̳̭r̛̗̘e͙p͠r̼̞̻̭̗e̺̠̣͟s̘͇̳͍̝͉e͉̥̯̞̲͚̬͜ǹ̬͎͎̟̖͇̤t͍̬̤͓̼̭͘ͅi̪̱n͠g̴͉ ͏͉ͅc̬̟h͡a̫̻̯͘o̫̟̖͍̙̝͉s̗̦̲.̨̹͈̣');
insert into products (name, quantity, price, description) values ('Britt', 'Harriot', 95, '1''; DROP TABLE users--');
insert into products (name, quantity, price, description) values ('Darren', 'Braunlein', 96, '1;DROP TABLE users');
insert into products (name, quantity, price, description) values ('Paolo', 'Andreucci', 60, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into products (name, quantity, price, description) values ('Ephraim', 'Lansberry', 4, 'Ω≈ç√∫˜µ≤≥÷');
insert into products (name, quantity, price, description) values ('Emmaline', 'Morfett', 85, '../../../../../../../../../../../etc/passwd%00');
insert into products (name, quantity, price, description) values ('Wilie', 'Anthoney', 79, '0/0');
