insert into products (name, quantity, price, description) values ('Allix', 1, 18, ',。・:*:・゜’( ☻ ω ☻ )。・:*:・゜’');
insert into products (name, quantity, price, description) values ('Andromache', 2, 2, '`⁄€‹›ﬁﬂ‡°·‚—±');
insert into products (name, quantity, price, description) values ('Anna-diana', 3, 44, 'Z̮̞̠͙͔ͅḀ̗̞͈̻̗Ḷ͙͎̯̹̞͓G̻O̭̗̮');
insert into products (name, quantity, price, description) values ('Kingston', 4, 63, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into products (name, quantity, price, description) values ('Melody', 5, 8, '社會科學院語學研究所');
insert into products (name, quantity, price, description) values ('Ashley', 6, 2, '✋🏿 💪🏿 👐🏿 🙌🏿 👏🏿 🙏🏿');
insert into products (name, quantity, price, description) values ('Rosalynd', 7, 42, 'パーティーへ行かないか');
insert into products (name, quantity, price, description) values ('Nichol', 8, 75, '"');
insert into products (name, quantity, price, description) values ('Ulysses', 9, 40, '(｡◕ ∀ ◕｡)');
insert into products (name, quantity, price, description) values ('Maurice', 10, 46, '() { 0; }; touch /tmp/blns.shellshock1.fail;');
insert into products (name, quantity, price, description) values ('Lu', 11, 69, '᠎');
insert into products (name, quantity, price, description) values ('Lissi', 12, 4, '''"''');
insert into products (name, quantity, price, description) values ('Averell', 13, 57, '␢');
insert into products (name, quantity, price, description) values ('Emalee', 14, 28, '울란바토르');
insert into products (name, quantity, price, description) values ('Caryl', 15, 48, '⁰⁴⁵₀₁₂');
insert into products (name, quantity, price, description) values ('Leon', 16, 90, '-1.00');
insert into products (name, quantity, price, description) values ('Prudy', 17, 54, '../../../../../../../../../../../etc/hosts');
insert into products (name, quantity, price, description) values ('Eydie', 18, 71, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into products (name, quantity, price, description) values ('Rodie', 19, 34, '・(￣∀￣)・:*:');
insert into products (name, quantity, price, description) values ('Dolf', 20, 95, 'בְּרֵאשִׁית, בָּרָא אֱלֹהִים, אֵת הַשָּׁמַיִם, וְאֵת הָאָרֶץ');
insert into products (name, quantity, price, description) values ('Lorin', 21, 28, '̡͓̞ͅI̗̘̦͝n͇͇͙v̮̫ok̲̫̙͈i̖͙̭̹̠̞n̡̻̮̣̺g̲͈͙̭͙̬͎ ̰t͔̦h̞̲e̢̤ ͍̬̲͖f̴̘͕̣è͖ẹ̥̩l͖͔͚i͓͚̦͠n͖͍̗͓̳̮g͍ ̨o͚̪͡f̘̣̬ ̖̘͖̟͙̮c҉͔̫͖͓͇͖ͅh̵̤̣͚͔á̗̼͕ͅo̼̣̥s̱͈̺̖̦̻͢.̛̖̞̠̫̰');
insert into products (name, quantity, price, description) values ('Cacilia', 22, 29, '999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999');
insert into products (name, quantity, price, description) values ('Luca', 23, 26, '''''');
insert into products (name, quantity, price, description) values ('Cletis', 24, 97, '-1/2');
insert into products (name, quantity, price, description) values ('Mirabella', 25, 72, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into products (name, quantity, price, description) values ('Danny', 26, 22, '1;DROP TABLE users');
insert into products (name, quantity, price, description) values ('Ingra', 27, 4, '-$1.00');
insert into products (name, quantity, price, description) values ('Lottie', 28, 64, '⁦test⁧');
insert into products (name, quantity, price, description) values ('Beilul', 29, 56, 'null');
insert into products (name, quantity, price, description) values ('Brocky', 30, 27, 'null');
insert into products (name, quantity, price, description) values ('Justis', 31, 50, '(ﾉಥ益ಥ）ﾉ﻿ ┻━┻');
insert into products (name, quantity, price, description) values ('Allyson', 32, 33, '﻿');
insert into products (name, quantity, price, description) values ('Ava', 33, 24, ' test ');
insert into products (name, quantity, price, description) values ('Tonia', 34, 33, null);
insert into products (name, quantity, price, description) values ('Elisha', 35, 63, '$1.00');
insert into products (name, quantity, price, description) values ('Karine', 36, 47, '👾 🙇 💁 🙅 🙆 🙋 🙎 🙍 ');
insert into products (name, quantity, price, description) values ('Dian', 37, 11, '0/0');
insert into products (name, quantity, price, description) values ('Gabi', 38, 54, 'ヽ༼ຈل͜ຈ༽ﾉ ヽ༼ຈل͜ຈ༽ﾉ ');
insert into products (name, quantity, price, description) values ('Celinda', 39, 79, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into products (name, quantity, price, description) values ('Frank', 40, 99, '<svg><script>0<1>alert(''XSS'')</script>');
insert into products (name, quantity, price, description) values ('Chane', 41, 29, '😍');
insert into products (name, quantity, price, description) values ('Salvidor', 42, 43, '社會科學院語學研究所');
insert into products (name, quantity, price, description) values ('Florentia', 43, 11, 'Ω≈ç√∫˜µ≤≥÷');
insert into products (name, quantity, price, description) values ('Mattie', 44, 17, '᠎');
insert into products (name, quantity, price, description) values ('Gorden', 45, 5, '˙ɐnbᴉlɐ ɐuƃɐɯ ǝɹolop ʇǝ ǝɹoqɐl ʇn ʇunpᴉpᴉɔuᴉ ɹodɯǝʇ poɯsnᴉǝ op pǝs ''ʇᴉlǝ ƃuᴉɔsᴉdᴉpɐ ɹnʇǝʇɔǝsuoɔ ''ʇǝɯɐ ʇᴉs ɹolop ɯnsdᴉ ɯǝɹo˥');
insert into products (name, quantity, price, description) values ('Guy', 46, 99, '울란바토르');
insert into products (name, quantity, price, description) values ('Sheeree', 47, 35, '"''"''"''''''''"');
insert into products (name, quantity, price, description) values ('Raymond', 48, 5, '1/0');
insert into products (name, quantity, price, description) values ('Emmeline', 49, 1, '1;DROP TABLE users');
insert into products (name, quantity, price, description) values ('Krisha', 50, 24, '和製漢語');
